### ISSUE TITLE
making .nnet a method of plot instead of plotnet

### ISSUE THREAD

**Issue by bquast** [fawda123/NeuralNetTools#10]
As you point out in your article:

> https://beckmw.wordpress.com/2013/11/14/visualizing-neural-networks-in-r-update/

the default plotting method for the neuralnet package is not ideal.

Wouldn't it be easier to just name the method

    plot.nnet

so that it overrides the included neuralnet plotting method. that way we could just:

    plot( neuralnet(...) )

**Comment by fawda123** [comment]
I'm not sure if it's possible to override an existing method for a generic function once all the packages are loaded.  The order of loading the packages can override generic functions but this doesn't seem to be true for methods.  I found a post on 
StackOverflow (http://stackoverflow.com/questions/13997122/override-s3-methods-in-base-r) that suggests creating a different class to override an existing method, which is kind of relevant to the problem here.  It seems simpler from a programming perspective just to create a new generic function that has methods that don't conflict with methods for the same class with another generic.

Method dispatch and namespaces confuse the hell out of me so I'm open to suggestions.

**Comment by mngreene** [comment]
Hi Marcus,

Hope all is well.

Just a quick questions hopefully regarding the NeuralNetTools - does it work all right to plot simple input-output no hidden layer networks? Tried with nnet output, got the following error message:

Error in seq.default(0.5 * (diff(y_range) + spacing * (lyr - 1)), 0.5 *  :
  'from' cannot be NA, NaN or infinite
In addition: Warning message:
In plotnet.nnet(results.NN1h0, nid = TRUE, all_out = TRUE, all_in = TRUE,  :
  Skip layer used, results may be inaccurate because input and output connections are removed

Regards,

Max Greene

________________________________

**Comment by fawda123** [comment]
Hi Max, 

I made some changes a while back so the functions would work with models that use skip layer connections.  Basically, the plots should work but they would only show the connections from I-H-O network.  So I'm concerned you're getting an error... could you post some code so that I can reproduce/fix the problem?  As is, the package does not allow plotting of only I-O layers - this would only make sense for skip layer models, and only part of the model.  I can try to sort this out if you're interested.  You can post an 'issue' on the issues tab if you'd like this feature added.

-Marcus

**Comment by mngreene** [comment]
Hi Marcus,


With the code below, if you set the size = 1+, plotting works fine. But if you change it to 0 with skip connections enabled, I get the error instead:

Error in data.frame(wts, row_nms) :

arguments imply differing number of rows: 3, 13)


----------------


require(nnet)


ird <- data.frame(rbind(iris3[,,1], iris3[,,2], iris3[,,3]),

                  species = factor(c(rep("s",50), rep("c", 50), rep("v", 50))))

ir.nn2 <- nnet(species ~ ., data = ird, subset = samp, size = 0, rang = 0.1,

               decay = 5e-4, maxit = 200, skip = TRUE)

summary(ir.nn2)



require(NeuralNetTools)

plotnet(ir.nn2, nid = TRUE, all_out = TRUE, all_in = TRUE,

        wts_only = FALSE, rel_rsc = 5, circle_cex = 5, node_labs = TRUE,

        var_labs = TRUE, x_lab = NULL, y_lab = NULL, line_stag = NULL,

        cex_val = 1, alpha_val = 1, circle_col = "lightblue",

        pos_col = "black", neg_col = "lightgrey", bord_col = "black",

        max_sp = TRUE)

-----------------

Hope this helps.

Regards,

Max

________________________________
