### ISSUE TITLE
Problems with lekprofile

### ISSUE THREAD

**Issue by matteodefelice** [fawda123/NeuralNetTools#2]
```
library(nnet)
library(NeuralNetTools)
> dd = data.frame(a = rnorm(100), b = runif(100), c = runif(100))
> f = nnet(a ~ b + c, data = dd, size = 4)
> lekprofile(f)
Error in apply(mat_cons, 2, fun_in) : dim(X) must have a positive length
```

Both on R version 3.1.1 on Red Hat Linux and R 3.1.2 on Mac Os X. 

_Update_ the error disappears if I have three inputs instead of two, i.e.
    > dd = data.frame(a = rnorm(100), b = runif(100), c = runif(100), d = runif(100))
    > f = nnet(a ~ b + c + d, data = dd, size = 4)

Now it works.

**Comment by matteodefelice** [comment]
How can install it?

**Comment by fawda123** [comment]
My fault for not updating the description file, should be okay now.  I don't think this affects the install though.  You'll have to install the GitHub version because the CRAN version is still 1.0.0.  I'm waiting to see if I get any more bug reports before I update the CRAN version.  Just follow the instructions in the README to install from GitHub as there are no tar.gz files or binaries to install from source in the repository.

**Comment by jhollist** [comment]
@fawda123 Just re-read my comment and it came off a bit snippy...  Sorry about that!  Was not my intent!
